config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server, at: '/cable'
  
  root :to => 'application#index'

  get '/articles/query', to: 'articles#query'
  get '/articles/all', to: 'articles#all'
  resources :articles
  resources :article_types
  resources :stories
  
  get 'hello_world', to: 'hello_world#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/article_types_controller.rb
class ArticleTypesController < ApplicationController
  before_action :set_article_type, only: [:show, :edit, :update, :destroy]

  # GET /article_types
  # GET /article_types.json
  def index
    @article_types = ArticleType.all
  end

  # GET /article_types/1
  # GET /article_types/1.json
  def show
  end

  # GET /article_types/new
  def new
    @article_type = ArticleType.new
  end

  # GET /article_types/1/edit
  def edit
  end

  # POST /article_types
  # POST /article_types.json
  def create
    @article_type = ArticleType.new(article_type_params)

    respond_to do |format|
      if @article_type.save
        format.html { redirect_to @article_type, notice: 'Article type was successfully created.' }
        format.json { render :show, status: :created, location: @article_type }
      else
        format.html { render :new }
        format.json { render json: @article_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /article_types/1
  # PATCH/PUT /article_types/1.json
  def update
    respond_to do |format|
      if @article_type.update(article_type_params)
        format.html { redirect_to @article_type, notice: 'Article type was successfully updated.' }
        format.json { render :show, status: :ok, location: @article_type }
      else
        format.html { render :edit }
        format.json { render json: @article_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /article_types/1
  # DELETE /article_types/1.json
  def destroy
    @article_type.destroy
    respond_to do |format|
      format.html { redirect_to article_types_url, notice: 'Article type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article_type
      @article_type = ArticleType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_type_params
      params.require(:article_type).permit(:type_name)
    end
end

app/helpers/article_types_helper.rb
module ArticleTypesHelper
end

app/views/article_types/_form.html.erb
<%= form_with(model: article_type, local: true) do |form| %>
  <% if article_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(article_type.errors.count, "error") %> prohibited this article_type from being saved:</h2>

      <ul>
        <% article_type.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :type_name %>
    <%= form.text_field :type_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/article_types/edit.html.erb
<h1>Editing Article Type</h1>

<%= render 'form', article_type: @article_type %>

<%= link_to 'Show', @article_type %> |
<%= link_to 'Back', article_types_path %>

app/views/article_types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Article Types</h1>

<table>
  <thead>
    <tr>
      <th>Type name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @article_types.each do |article_type| %>
      <tr>
        <td><%= article_type.type_name %></td>
        <td><%= link_to 'Show', article_type %></td>
        <td><%= link_to 'Edit', edit_article_type_path(article_type) %></td>
        <td><%= link_to 'Destroy', article_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Article Type', new_article_type_path %>

app/views/article_types/new.html.erb
<h1>New Article Type</h1>

<%= render 'form', article_type: @article_type %>

<%= link_to 'Back', article_types_path %>

app/views/article_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Type name:</strong>
  <%= @article_type.type_name %>
</p>

<%= link_to 'Edit', edit_article_type_path(@article_type) %> |
<%= link_to 'Back', article_types_path %>